openapi: "3.0.0"
info:
  title: "Learn Swagger"
  description: "Segment about writing docs"
  version: "1.0.0"
  contact:
    email: rb@gmail.com
    url: "https://riteshbenjwal.dev"



# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: Local  - secure
#   - url: "http://localhost:4000/api/v1"
#     description: Local Host - regular


servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: Local  - secure
    variables: 
      version:
        enum:
          - v1
          - v2
      protocol:
        enum:
          - http
          - https
